FROM ubuntu:20.04
LABEL email="bonhyeon.gu@9bon.org"
LABEL name="BonhyeonGu"
ENV TZ=Asia/Seoul
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt update
RUN apt install -y ffmpeg cron

#Time-------------------------------------------------------
RUN apt-get install -y git tzdata python3 python3-pip fuse nano
RUN apt install -y python3-opencv rclone
RUN pip3 install numpy pysftp
RUN echo $TZ > /etc/timezone && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    apt-get clean
#-----------------------------------------------------------

WORKDIR /root
RUN git clone https://github.com/BonhyeonGu/png2mp4RandWeb p

WORKDIR /root/p
RUN mkdir cmd
RUN mkdir /source
COPY ./setting.json ./
ENTRYPOINT ["/bin/sh", "-c" , "python3 app_0_remote.py"]

#rclone config
#https://cloud.9bon.org/remote.php/dav/files/whwhdtk
#rclone mount remote:/_Share/_Lock/VRC /source --read-only --daemon --vfs-cache-mode full --vfs-cache-max-size 20G && touch cmd/START
#rclone lsd remote:/_Share/_Lock/VRC
