version: "3"
services:
  png2mp4_agent:
    tty: true
    stdin_open: true
    container_name: png2mp4_agent
    build:
      context: .
      dockerfile: ./Dockerfile_0
    environment:
        TZ: "Asia/Seoul"
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/ubuntu/Docker/png2mp4/vol:/source
