version: "3"
services:
  pngpick:
    tty: true
    stdin_open: true
    container_name: pngpick
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /volume1/homes/minfree/Photos/VRChat:/in 
      - /volume1/web/images:/out